# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

py_binary(
    name = "expand_cmake_vars",
    srcs = ["expand_cmake_vars.py"],
    srcs_version = "PY2AND3",
    visibility = ["@llvm-project//:__subpackages__"],
)
