# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

workspace(name = "llvm_bazel")

load(":configure.bzl", "llvm_configure")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


llvm_configure(
    name = "llvm-project",
    overlay_path = "llvm-project-overlay",
    src_path = "../third_party/llvm-project",
)


http_archive(
    name = "zlib",
    build_file = "//third_party_build:zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = [
        "https://storage.googleapis.com/mirror.tensorflow.org/zlib.net/zlib-1.2.11.tar.gz",
        "https://zlib.net/zlib-1.2.11.tar.gz",
    ],
)
